on: [push]
jobs:
  go-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.14", "1.13", "1.12"]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go build -x -work ./cmds/...
  node-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
  docker-build:
    name: Create docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Build hound
        run: go build -x -work ./cmds/... 
      - name: Build ui
        run: npm install
      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: inful/hound/hound
          tag_with_ref: true
  golangci:
    name: lint
    strategy:
      matrix:
        go: ["1.14"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          # the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.35.2
  go-test:
    strategy:
      matrix:
        go: ["1.14", "1.13", "1.12"]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test -race ./...
  # There are no npm tests, yet.
